# Copyright 2022 - 2025 SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

name: check
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read
defaults:
  run:
    shell: bash
    working-directory: ./rust/
env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings
jobs:
  fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1.14.1
      - name: Check formatting
        run: cargo fmt --check --all
  clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/install-deps
      - uses: actions-rust-lang/setup-rust-toolchain@v1.14.1
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: cargo clippy
        run: cargo clippy --locked --all-targets --all-features --workspace
  doc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/install-deps
      - uses: actions-rust-lang/setup-rust-toolchain@v1.14.1
        with:
          toolchain: nightly
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install cargo-docs-rs
        uses: dtolnay/install@cargo-docs-rs
      - run: cargo docs-rs --locked -p edgehog-device-runtime-proto

  features:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/install-deps
      - uses: actions-rust-lang/setup-rust-toolchain@v1.14.1
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: cargo install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: cargo hack test interfaces
        run: cargo hack --each-feature test --locked
  minimal-versions:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/install-deps
      - name: install rust stable
        uses: actions-rust-lang/setup-rust-toolchain@v1.14.1
      - name: install rust nightly
        uses: actions-rust-lang/setup-rust-toolchain@v1.14.1
        with:
          toolchain: nightly
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: taiki-e/install-action@v2.58.30
        with:
          tool: cargo-hack,cargo-minimal-versions
      - run: rustup default stable
      - name: Check minimal versions
        run: cargo minimal-versions check --workspace --ignore-private --detach-path-deps=skip-exact --direct
  msrv:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        msrv: [1.78]
    name: msrv / ${{ matrix.msrv }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/install-deps
      - uses: actions-rust-lang/setup-rust-toolchain@v1.14.1
        with:
          toolchain: ${{ matrix.msrv }}
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: taiki-e/install-action@cargo-hack
      - name: cargo +${{ matrix.msrv }} check
        run: cargo +${{ matrix.msrv }} hack --no-dev-deps check --all-features
  # Run semver-check on release branch push or PR
  semver:
    if: startsWith(github.base_ref, 'release-') || startsWith(github.ref, 'release-')
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1.14.1
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Check library API semver breakages
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          release-type: patch
  # Check that the create can be compiled with only the packaged files
  for-publish:
    name: stable / for-publish
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/install-deps
      - uses: actions-rust-lang/setup-rust-toolchain@v1.14.1
      - uses: mozilla-actions/sccache-action@v0.0.9
      - run: ../scripts/check-for-publish.sh
